language: ruby
branches:
  only:
  - master
rvm:
- 2.4.0
install:
- git config --global user.email "github_bot@segiddins.me"
- git config --global user.name "GiddinsBot"
- rake bootstrap
script:
- git remote set-url origin "https://${GH_TOKEN}@github.com/segiddins/segiddins.me.git"
- bundle exec rake deploy
env:
  global:
    secure: JTo86WxqU//WnN8h/p7mFuuLQQdCEO55EIHp07j9zJE46IYCdeCAglIjdjfjn64NGGLXNlHYFL/EIYVevQL+HkPfe/v9X9I1z/UKuqH2yRW1ajryLdLSffrBh+veN/0IlkzmzzWcKq8w91KlzYsHVnFqjgpbvSCwKC+2MoLLu6k=
